# GoReleaser configuration
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: gossm
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.gossmVersion={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: tommy-cxcpwz
    name: gossm

brews:
  - name: gossm
    repository:
      owner: tommy-cxcpwz
      name: homebrew-gossm
    commit_author:
      name: tommy-cxcpwz
      email: tommy-cxcpwz@users.noreply.github.com
    homepage: "https://github.com/tommy-cxcpwz/gossm"
    description: "Interactive CLI tool to connect to AWS EC2 instances via AWS Systems Manager Session Manager"
    license: "MIT"
